import Link from "next/link";
import { Bookmark, ExternalLink } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export default async function SavedKeywordsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: keywords } = user ? await supabase.from("keywords").select("id,keyword,intent,difficulty,opportunity,created_at,project_id").eq("user_id", user.id).eq("is_saved", true).order("created_at", { ascending: false }) : { data: [] };
  return <div><div><p className="text-sm text-violet-300">Library</p><h1 className="mt-1 text-3xl font-bold text-white">Saved keywords</h1><p className="mt-2 text-slate-400">Your curated keyword opportunities.</p></div>{!user ? <div className="mt-8 rounded-2xl border border-white/10 p-8 text-center text-slate-300">Sign in to access your saved keywords.<br/><Link href="/login" className="mt-3 inline-block text-violet-300">Go to login</Link></div> : keywords?.length ? <div className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="grid grid-cols-[1fr_130px_100px_100px] gap-4 border-b border-white/10 px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-500"><span>Keyword</span><span>Intent</span><span>Difficulty</span><span>Opportunity</span></div>{keywords.map((item) => <div key={item.id} className="grid grid-cols-[1fr_130px_100px_100px] items-center gap-4 border-b border-white/5 px-5 py-4 text-sm last:border-0"><span className="font-medium text-white">{item.keyword}</span><span className="text-slate-400">{item.intent || "—"}</span><span className="text-slate-300">{item.difficulty ?? "—"}</span><span className="text-emerald-300">{item.opportunity ?? "—"}</span></div>)}</div> : <div className="mt-8 rounded-2xl border border-dashed border-white/15 p-12 text-center"><Bookmark className="mx-auto size-10 text-slate-500"/><h2 className="mt-4 font-semibold text-white">Nothing saved yet</h2><p className="mt-2 text-sm text-slate-400">Run keyword research and save the opportunities you want to revisit.</p><Link href="/dashboard/research" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-violet-300">Start research <ExternalLink className="size-4"/></Link></div>}</div>;
}
